name: Node.js CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.2] # Updated to your local Node.js version

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Diagnostic steps to print out versions
    - run: node -v
    - run: npm -v

    - name: Install Dependencies
      run: npm install

    # Removed the npm ci step since npm install is used

    - run: npm run build --if-present
    - run: npm test -- --watchAll=false
